name: weather_forecast
description: 24 Hours Code Challenge | Weather Forecast.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_dotenv: ^5.0.2
  auth0_flutter: ^1.0.2
  http: ^0.13.5
  flutter_secure_storage: ^7.0.1
  intl: ^0.18.0
  unities_helper: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
